from app.core.database import Base
from app.models.agency import (
    Disbursement,
    DisbursementStatus,
    ManagementAgreement,
    ManagementAgreementStatus,
    OwnerProfile,
    TerminationParty,
)
from app.models.ai_analysis import (
    LeaseAnalysis,
    LeaseSuggestion,
    LeaseSuggestionCategory,
    LeaseSuggestionStatus,
)
from app.models.application import (
    APPLICATION_TRANSITIONS,
    OPEN_APPLICATION_STATUSES,
    ApplicationRejectionReason,
    ApplicationStatus,
    EmploymentStatus,
    Guarantor,
    GuarantorStatus,
    ReferenceCheck,
    ReferenceStatus,
    TenantApplication,
)
from app.models.approval import (
    ApprovalAction,
    ApprovalActionType,
    ApprovalRequest,
    ApprovalRequestStatus,
    ApprovalRule,
)
from app.models.asset import (
    AgreementStatus,
    AssetKind,
    AssetStatus,
    FuelPolicy,
    RateBasis,
    RentalAgreement,
    RentalAsset,
)
from app.models.audit import AuditLog
from app.models.billing import (
    Invoice,
    InvoiceLineItem,
    InvoiceStatus,
    LineItemKind,
    Payment,
    PaymentMethod,
    PaymentStatus,
    Receipt,
)
from app.models.bulk import BulkOperation, BulkOperationKind, BulkOperationStatus
from app.models.communication import CommunicationTemplate, TemplateChannel
from app.models.demo import DemoDataset
from app.models.developer import (
    ApiKey,
    ApiKeyScope,
    WebhookDelivery,
    WebhookDeliveryStatus,
    WebhookEndpoint,
    WebhookEvent,
)
from app.models.etims import EtimsCredential, EtimsStatus, EtimsSubmission
from app.models.facilities import (
    Amenity,
    AmenityBooking,
    AmenityKind,
    BayType,
    BookingStatus,
    ComplianceItem,
    ComplianceStatus,
    ComplianceType,
    ParkingAllocation,
    ParkingBay,
    UtilityAccount,
    UtilityAccountType,
    UtilityPaymentStatus,
)
from app.models.file import FileCategory, ScanStatus, StoredFile, UploadStatus
from app.models.inspection import InspectionReport, InspectionStatus, InspectionType, RoomCondition
from app.models.integrations import (
    AccountingConnection,
    AccountingEntityType,
    AccountingProvider,
    AccountingSyncRecord,
    AccountingSyncStatus,
    BankStatementEntry,
    BankStatementUpload,
    PortalConnection,
    PortalListingSync,
    PortalName,
    PortalSyncStatus,
)
from app.models.legal_hold import LegalHold
from app.models.notification import (
    DeliveryStatus,
    EmailSuppression,
    EmailSuppressionReason,
    Notification,
    NotificationChannel,
    NotificationPreference,
    NotificationType,
    PushSubscription,
)
from app.models.operations import (
    ALLOWED_TRANSITIONS,
    BILLABLE_STATUSES,
    OPEN_STATUSES,
    MaintenanceCategory,
    MaintenancePriority,
    MaintenanceRequest,
    MaintenanceStatus,
    MeterReading,
    MeterType,
    RejectionReason,
    VacateNotice,
    VacateNoticeStatus,
    VisitorLog,
)
from app.models.organization import (
    OperatingMode,
    Organization,
    OrganizationEncryptionKey,
    ReportDeliveryChannel,
    SubscriptionPlan,
)
from app.models.privacy import DataRequest, DataRequestStatus, DataRequestType
from app.models.property import (
    CaretakerAssignment,
    LateFeeType,
    Property,
    PropertyType,
    Unit,
    UnitStatus,
)
from app.models.renewal import LeaseRenewal, RenewalStatus
from app.models.reporting import (
    MonthlyReport,
    ReportChartType,
    ReportDefinition,
    ReportExportFormat,
    ReportSchedule,
)
from app.models.saved_view import SavedView
from app.models.security import (
    BREACH_NOTIFICATION_WINDOW_HOURS,
    NOTIFIABLE_SEVERITIES,
    BreachCategory,
    BreachSeverity,
    BreachStatus,
    FraudAlert,
    FraudAlertStatus,
    FraudAlertType,
    FraudSuppression,
    SecurityBreach,
    SecurityEvent,
    SecurityEventType,
)
from app.models.service_charge import (
    Apportionment,
    ServiceChargeBudget,
    ServiceChargeCategory,
    ServiceChargeExpense,
    ServiceChargeScheme,
    SinkingFundEntry,
    SinkingFundMovement,
    UseClass,
)
from app.models.session import (
    Invitation,
    InvitationStatus,
    TokenPurpose,
    TrustedDevice,
    UserSession,
    VerificationToken,
)
from app.models.signature import DigitalSignature, SignatureStatus
from app.models.subscription import (
    BillingInterval,
    Subscription,
    SubscriptionInvoice,
    SubscriptionInvoiceStatus,
    SubscriptionStatus,
)
from app.models.task_run import TaskRun, TaskRunStatus
from app.models.tenant import (
    LeaseTemplate,
    PaymentMethodPreference,
    Tenancy,
    TenancyCoTenant,
    TenancyStatus,
    Tenant,
)
from app.models.user import User, UserRole
from app.models.vacancy import (
    DataExport,
    ExportFormat,
    ExportKind,
    Inquiry,
    LeadStage,
    ListingStatus,
    VacancyListing,
)
from app.models.vendor import CATEGORY_SPECIALTIES, Vendor, VendorSpecialty
from app.models.webauthn import WebauthnCredential

__all__ = [
    "ALLOWED_TRANSITIONS",
    "APPLICATION_TRANSITIONS",
    "BILLABLE_STATUSES",
    "BREACH_NOTIFICATION_WINDOW_HOURS",
    "CATEGORY_SPECIALTIES",
    "NOTIFIABLE_SEVERITIES",
    "OPEN_APPLICATION_STATUSES",
    "OPEN_STATUSES",
    "AccountingConnection",
    "AccountingEntityType",
    "AccountingProvider",
    "AccountingSyncRecord",
    "AccountingSyncStatus",
    "AgreementStatus",
    "Amenity",
    "AmenityBooking",
    "AmenityKind",
    "ApiKey",
    "ApiKeyScope",
    "ApplicationRejectionReason",
    "ApplicationStatus",
    "Apportionment",
    "ApprovalAction",
    "ApprovalActionType",
    "ApprovalRequest",
    "ApprovalRequestStatus",
    "ApprovalRule",
    "AssetKind",
    "AssetStatus",
    "AuditLog",
    "BankStatementEntry",
    "BankStatementUpload",
    "Base",
    "BayType",
    "BillingInterval",
    "BookingStatus",
    "BreachCategory",
    "BreachSeverity",
    "BreachStatus",
    "BulkOperation",
    "BulkOperationKind",
    "BulkOperationStatus",
    "CaretakerAssignment",
    "CommunicationTemplate",
    "ComplianceItem",
    "ComplianceStatus",
    "ComplianceType",
    "DataExport",
    "DataRequest",
    "DataRequestStatus",
    "DataRequestType",
    "DeliveryStatus",
    "DemoDataset",
    "DigitalSignature",
    "Disbursement",
    "DisbursementStatus",
    "EmailSuppression",
    "EmailSuppressionReason",
    "EmploymentStatus",
    "EtimsCredential",
    "EtimsStatus",
    "EtimsSubmission",
    "ExportFormat",
    "ExportKind",
    "FileCategory",
    "FraudAlert",
    "FraudAlertStatus",
    "FraudAlertType",
    "FraudSuppression",
    "FuelPolicy",
    "Guarantor",
    "GuarantorStatus",
    "Inquiry",
    "InspectionReport",
    "InspectionStatus",
    "InspectionType",
    "Invitation",
    "InvitationStatus",
    "Invoice",
    "InvoiceLineItem",
    "InvoiceStatus",
    "LateFeeType",
    "LeadStage",
    "LeaseAnalysis",
    "LeaseRenewal",
    "LeaseSuggestion",
    "LeaseSuggestionCategory",
    "LeaseSuggestionStatus",
    "LeaseTemplate",
    "LegalHold",
    "LineItemKind",
    "ListingStatus",
    "MaintenanceCategory",
    "MaintenancePriority",
    "MaintenanceRequest",
    "MaintenanceStatus",
    "ManagementAgreement",
    "ManagementAgreementStatus",
    "MeterReading",
    "MeterType",
    "MonthlyReport",
    "Notification",
    "NotificationChannel",
    "NotificationPreference",
    "NotificationType",
    "OperatingMode",
    "Organization",
    "OrganizationEncryptionKey",
    "OwnerProfile",
    "ParkingAllocation",
    "ParkingBay",
    "Payment",
    "PaymentMethod",
    "PaymentMethodPreference",
    "PaymentStatus",
    "PortalConnection",
    "PortalListingSync",
    "PortalName",
    "PortalSyncStatus",
    "Property",
    "PropertyType",
    "PushSubscription",
    "RateBasis",
    "Receipt",
    "ReferenceCheck",
    "ReferenceStatus",
    "RejectionReason",
    "RenewalStatus",
    "RentalAgreement",
    "RentalAsset",
    "ReportChartType",
    "ReportDefinition",
    "ReportDeliveryChannel",
    "ReportExportFormat",
    "ReportSchedule",
    "RoomCondition",
    "SavedView",
    "ScanStatus",
    "SecurityBreach",
    "SecurityEvent",
    "SecurityEventType",
    "ServiceChargeBudget",
    "ServiceChargeCategory",
    "ServiceChargeExpense",
    "ServiceChargeScheme",
    "SignatureStatus",
    "SinkingFundEntry",
    "SinkingFundMovement",
    "StoredFile",
    "Subscription",
    "SubscriptionInvoice",
    "SubscriptionInvoiceStatus",
    "SubscriptionPlan",
    "SubscriptionStatus",
    "TaskRun",
    "TaskRunStatus",
    "TemplateChannel",
    "Tenancy",
    "TenancyCoTenant",
    "TenancyStatus",
    "Tenant",
    "TenantApplication",
    "TerminationParty",
    "TokenPurpose",
    "TrustedDevice",
    "Unit",
    "UnitStatus",
    "UploadStatus",
    "UseClass",
    "User",
    "UserRole",
    "UserSession",
    "UtilityAccount",
    "UtilityAccountType",
    "UtilityPaymentStatus",
    "VacancyListing",
    "VacateNotice",
    "VacateNoticeStatus",
    "Vendor",
    "VendorSpecialty",
    "VerificationToken",
    "VisitorLog",
    "WebauthnCredential",
    "WebhookDelivery",
    "WebhookDeliveryStatus",
    "WebhookEndpoint",
    "WebhookEvent",
]
