"""phase 1: portfolio, tenancy, billing, operations, notifications

Revision ID: becdc2a16b45
Revises: 978bef97001b
Create Date: 2026-09-03 07:02:10.469010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "becdc2a16b45"
down_revision: Union[str, None] = "978bef97001b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stored_files",
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "PROPERTY_PHOTO",
                "UNIT_PHOTO",
                "TENANT_ID",
                "TENANT_PASSPORT_PHOTO",
                "LEASE",
                "RECEIPT",
                "INVOICE",
                "METER_READING",
                "MAINTENANCE",
                "NOTICE",
                "ORG_LOGO",
                "PROFILE_PHOTO",
                "OTHER",
                name="file_category",
            ),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("PENDING", "UPLOADED", "FAILED", name="upload_status"), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supersedes_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stored_files_entity_id"), "stored_files", ["entity_id"], unique=False)
    op.create_index(op.f("ix_stored_files_entity_type"), "stored_files", ["entity_type"], unique=False)
    op.create_index(
        op.f("ix_stored_files_organization_id"), "stored_files", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_stored_files_storage_key"), "stored_files", ["storage_key"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("actor_name", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.String(length=512), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("gps_latitude", sa.Float(), nullable=True),
        sa.Column("gps_longitude", sa.Float(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index("ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False)
    op.create_index(
        "ix_audit_logs_org_created", "audit_logs", ["organization_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("property_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REVOKED", "EXPIRED", name="invitation_status"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by_id", sa.UUID(), nullable=True),
        sa.Column("accepted_user_id", sa.UUID(), nullable=True),
        sa.Column("cash_limit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["accepted_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["invited_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invitations_organization_id"), "invitations", ["organization_id"], unique=False)
    op.create_index(op.f("ix_invitations_phone_number"), "invitations", ["phone_number"], unique=False)
    op.create_index(op.f("ix_invitations_token_hash"), "invitations", ["token_hash"], unique=True)
    op.create_table(
        "lease_templates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("logo_file_id", sa.UUID(), nullable=True),
        sa.Column("letterhead_text", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["logo_file_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lease_templates_organization_id"), "lease_templates", ["organization_id"], unique=False
    )
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "PAYMENT_CONFIRMED",
                "RENT_REMINDER",
                "INVOICE_ISSUED",
                "RECEIPT_ISSUED",
                "MAINTENANCE_UPDATE",
                "MAINTENANCE_SUBMITTED",
                "LEASE_EXPIRY",
                "TRIAL_EXPIRY",
                "UNIT_STATUS_CHANGED",
                "SUSPICIOUS_LOGIN",
                "VACATE_NOTICE",
                "CARETAKER_DAILY_SUMMARY",
                "WELCOME",
                "ACCOUNT",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("WHATSAPP", "SMS", "PUSH", "EMAIL", "IN_APP", name="notification_channel"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "notification_type", "channel", name="uq_notification_preference"),
    )
    op.create_index(
        op.f("ix_notification_preferences_organization_id"),
        "notification_preferences",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"), "notification_preferences", ["user_id"], unique=False
    )
    op.create_table(
        "properties",
        sa.Column("reference_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "property_type",
            sa.Enum(
                "RESIDENTIAL",
                "COMMERCIAL",
                "MIXED_USE",
                "VEHICLE_FLEET",
                "EQUIPMENT",
                "EVENT_SPACE",
                "LAND",
                name="property_type",
            ),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=512), nullable=False),
        sa.Column("county", sa.String(length=128), nullable=True),
        sa.Column("sub_county", sa.String(length=128), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amenities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("water_rate_per_unit", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("electricity_rate_per_unit", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("grace_period_days", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "reference_code", name="uq_property_ref_per_org"),
    )
    op.create_index(op.f("ix_properties_county"), "properties", ["county"], unique=False)
    op.create_index(op.f("ix_properties_is_archived"), "properties", ["is_archived"], unique=False)
    op.create_index(op.f("ix_properties_organization_id"), "properties", ["organization_id"], unique=False)
    op.create_index(op.f("ix_properties_reference_code"), "properties", ["reference_code"], unique=False)
    op.create_table(
        "push_subscriptions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh_key", sa.String(length=255), nullable=False),
        sa.Column("auth_key", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_index(
        op.f("ix_push_subscriptions_organization_id"), "push_subscriptions", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("reference_code", sa.String(length=32), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("national_id", sa.String(length=64), nullable=True),
        sa.Column("id_photo_front_id", sa.UUID(), nullable=True),
        sa.Column("id_photo_back_id", sa.UUID(), nullable=True),
        sa.Column("passport_photo_id", sa.UUID(), nullable=True),
        sa.Column("employer_name", sa.String(length=255), nullable=True),
        sa.Column("occupation", sa.String(length=255), nullable=True),
        sa.Column("monthly_income", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=255), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=32), nullable=True),
        sa.Column("emergency_contact_relationship", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("portal_user_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["id_photo_back_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["id_photo_front_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["passport_photo_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["portal_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "phone_number", name="uq_tenant_phone_per_org"),
        sa.UniqueConstraint("organization_id", "reference_code", name="uq_tenant_ref_per_org"),
        sa.UniqueConstraint("portal_user_id"),
    )
    op.create_index(op.f("ix_tenants_email"), "tenants", ["email"], unique=False)
    op.create_index(op.f("ix_tenants_full_name"), "tenants", ["full_name"], unique=False)
    op.create_index(op.f("ix_tenants_is_archived"), "tenants", ["is_archived"], unique=False)
    op.create_index(op.f("ix_tenants_national_id"), "tenants", ["national_id"], unique=False)
    op.create_index(op.f("ix_tenants_organization_id"), "tenants", ["organization_id"], unique=False)
    op.create_index(op.f("ix_tenants_phone_number"), "tenants", ["phone_number"], unique=False)
    op.create_index(op.f("ix_tenants_reference_code"), "tenants", ["reference_code"], unique=False)
    op.create_table(
        "trusted_devices",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("device_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("device_name", sa.String(length=255), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trusted_devices_device_fingerprint"), "trusted_devices", ["device_fingerprint"], unique=False
    )
    op.create_index(
        op.f("ix_trusted_devices_organization_id"), "trusted_devices", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_trusted_devices_user_id"), "trusted_devices", ["user_id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=128), nullable=False),
        sa.Column("device_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("device_name", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_sessions_device_fingerprint"), "user_sessions", ["device_fingerprint"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_organization_id"), "user_sessions", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_refresh_token_hash"), "user_sessions", ["refresh_token_hash"], unique=False
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "verification_tokens",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum("EMAIL_VERIFICATION", "PASSWORD_RESET", "TENANT_PORTAL_INVITE", name="token_purpose"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_tokens_token_hash"), "verification_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_verification_tokens_user_id"), "verification_tokens", ["user_id"], unique=False)
    op.create_table(
        "caretaker_assignments",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("cash_limit", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "property_id", name="uq_caretaker_property"),
    )
    op.create_index(
        op.f("ix_caretaker_assignments_organization_id"),
        "caretaker_assignments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_caretaker_assignments_property_id"), "caretaker_assignments", ["property_id"], unique=False
    )
    op.create_index(
        op.f("ix_caretaker_assignments_user_id"), "caretaker_assignments", ["user_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column(
            "channel",
            sa.Enum("WHATSAPP", "SMS", "PUSH", "EMAIL", "IN_APP", name="notification_channel"),
            nullable=False,
        ),
        sa.Column(
            "notification_type",
            sa.Enum(
                "PAYMENT_CONFIRMED",
                "RENT_REMINDER",
                "INVOICE_ISSUED",
                "RECEIPT_ISSUED",
                "MAINTENANCE_UPDATE",
                "MAINTENANCE_SUBMITTED",
                "LEASE_EXPIRY",
                "TRIAL_EXPIRY",
                "UNIT_STATUS_CHANGED",
                "SUSPICIOUS_LOGIN",
                "VACATE_NOTICE",
                "CARETAKER_DAILY_SUMMARY",
                "WELCOME",
                "ACCOUNT",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("recipient", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("link_path", sa.String(length=512), nullable=True),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "SENT", "DELIVERED", "FAILED", "SKIPPED", name="delivery_status"),
            nullable=False,
        ),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("error", sa.String(length=512), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_notification_type"), "notifications", ["notification_type"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_organization_id"), "notifications", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_tenant_id"), "notifications", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "units",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("reference_code", sa.String(length=32), nullable=False),
        sa.Column("unit_number", sa.String(length=64), nullable=False),
        sa.Column("unit_type", sa.String(length=64), nullable=True),
        sa.Column("size_sqm", sa.Float(), nullable=True),
        sa.Column("floor", sa.String(length=32), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Integer(), nullable=True),
        sa.Column("monthly_rent", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("deposit_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("VACANT", "OCCUPIED", "UNDER_MAINTENANCE", "RESERVED", "VACATING", name="unit_status"),
            nullable=False,
        ),
        sa.Column("vacancy_date", sa.Date(), nullable=True),
        sa.Column("expected_vacancy_date", sa.Date(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "reference_code", name="uq_unit_ref_per_org"),
        sa.UniqueConstraint("property_id", "unit_number", name="uq_unit_number_per_property"),
    )
    op.create_index(op.f("ix_units_is_archived"), "units", ["is_archived"], unique=False)
    op.create_index(op.f("ix_units_organization_id"), "units", ["organization_id"], unique=False)
    op.create_index(op.f("ix_units_property_id"), "units", ["property_id"], unique=False)
    op.create_index(op.f("ix_units_reference_code"), "units", ["reference_code"], unique=False)
    op.create_index(op.f("ix_units_status"), "units", ["status"], unique=False)
    op.create_table(
        "tenancies",
        sa.Column("reference_code", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_open_ended", sa.Boolean(), nullable=False),
        sa.Column("monthly_rent", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("deposit_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("billing_day", sa.Integer(), nullable=False),
        sa.Column("notice_period_days", sa.Integer(), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum("MPESA", "BANK_TRANSFER", "CASH", "CHEQUE", name="payment_method_preference"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "EXPIRING_SOON", "EXPIRED", "NOTICE_GIVEN", "VACATED", name="tenancy_status"),
            nullable=False,
        ),
        sa.Column("notice_given_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("move_out_date", sa.Date(), nullable=True),
        sa.Column("vacated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_document_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["lease_document_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "reference_code", name="uq_tenancy_ref_per_org"),
    )
    op.create_index(op.f("ix_tenancies_end_date"), "tenancies", ["end_date"], unique=False)
    op.create_index(op.f("ix_tenancies_organization_id"), "tenancies", ["organization_id"], unique=False)
    op.create_index(op.f("ix_tenancies_reference_code"), "tenancies", ["reference_code"], unique=False)
    op.create_index(op.f("ix_tenancies_status"), "tenancies", ["status"], unique=False)
    op.create_index(op.f("ix_tenancies_tenant_id"), "tenancies", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_tenancies_unit_id"), "tenancies", ["unit_id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("reference_code", sa.String(length=32), nullable=False),
        sa.Column("tenancy_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PARTIALLY_PAID", "PAID", "OVERDUE", "CANCELLED", name="invoice_status"),
            nullable=False,
        ),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenancy_id"], ["tenancies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "reference_code", name="uq_invoice_ref_per_org"),
        sa.UniqueConstraint("tenancy_id", "period_start", name="uq_invoice_period_per_tenancy"),
    )
    op.create_index(op.f("ix_invoices_due_date"), "invoices", ["due_date"], unique=False)
    op.create_index(op.f("ix_invoices_organization_id"), "invoices", ["organization_id"], unique=False)
    op.create_index(op.f("ix_invoices_reference_code"), "invoices", ["reference_code"], unique=False)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_index(op.f("ix_invoices_tenancy_id"), "invoices", ["tenancy_id"], unique=False)
    op.create_table(
        "maintenance_requests",
        sa.Column("reference_code", sa.String(length=32), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("tenancy_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "PLUMBING",
                "ELECTRICAL",
                "STRUCTURAL",
                "APPLIANCE",
                "SECURITY",
                "OTHER",
                name="maintenance_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Enum("EMERGENCY", "URGENT", "ROUTINE", name="maintenance_priority"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "SUBMITTED",
                "ACKNOWLEDGED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="maintenance_status",
            ),
            nullable=False,
        ),
        sa.Column("photo_file_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reported_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reported_by_tenant_id", sa.UUID(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reported_by_tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reported_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenancy_id"], ["tenancies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "reference_code", name="uq_maintenance_ref_per_org"),
    )
    op.create_index(
        op.f("ix_maintenance_requests_organization_id"),
        "maintenance_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_requests_reference_code"),
        "maintenance_requests",
        ["reference_code"],
        unique=False,
    )
    op.create_index(op.f("ix_maintenance_requests_status"), "maintenance_requests", ["status"], unique=False)
    op.create_index(
        op.f("ix_maintenance_requests_unit_id"), "maintenance_requests", ["unit_id"], unique=False
    )
    op.create_table(
        "vacate_notices",
        sa.Column("tenancy_id", sa.UUID(), nullable=False),
        sa.Column("move_out_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("notice_days_given", sa.Integer(), nullable=False),
        sa.Column("meets_notice_period", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SUBMITTED", "ACKNOWLEDGED", "WITHDRAWN", "COMPLETED", name="vacate_notice_status"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("submitted_by_tenant_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submitted_by_tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenancy_id"], ["tenancies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vacate_notices_organization_id"), "vacate_notices", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_vacate_notices_tenancy_id"), "vacate_notices", ["tenancy_id"], unique=False)
    op.create_table(
        "invoice_line_items",
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "RENT",
                "WATER",
                "ELECTRICITY",
                "SERVICE_CHARGE",
                "ARREARS",
                "LATE_FEE",
                "DEPOSIT",
                "OTHER",
                name="line_item_kind",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoice_line_items_invoice_id"), "invoice_line_items", ["invoice_id"], unique=False
    )
    op.create_table(
        "meter_readings",
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("meter_type", sa.Enum("WATER", "ELECTRICITY", name="meter_type"), nullable=False),
        sa.Column("previous_reading", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("current_reading", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("consumption", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reading_date", sa.Date(), nullable=False),
        sa.Column("photo_file_id", sa.UUID(), nullable=True),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column("gps_latitude", sa.Float(), nullable=True),
        sa.Column("gps_longitude", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("billed_invoice_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["billed_invoice_id"], ["invoices.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["photo_file_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recorded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unit_id", "meter_type", "reading_date", name="uq_reading_per_unit_per_day"),
    )
    op.create_index(
        op.f("ix_meter_readings_organization_id"), "meter_readings", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_meter_readings_reading_date"), "meter_readings", ["reading_date"], unique=False)
    op.create_index(op.f("ix_meter_readings_unit_id"), "meter_readings", ["unit_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("reference_code", sa.String(length=32), nullable=False),
        sa.Column("tenancy_id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "method",
            sa.Enum("MPESA", "CASH", "BANK_TRANSFER", "CHEQUE", name="payment_method"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "FAILED", "CANCELLED", "REVERSED", name="payment_status"),
            nullable=False,
        ),
        sa.Column("mpesa_receipt", sa.String(length=64), nullable=True),
        sa.Column("mpesa_checkout_request_id", sa.String(length=128), nullable=True),
        sa.Column("mpesa_merchant_request_id", sa.String(length=128), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("failure_reason", sa.String(length=512), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recorded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenancy_id"], ["tenancies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "reference_code", name="uq_payment_ref_per_org"),
    )
    op.create_index(op.f("ix_payments_invoice_id"), "payments", ["invoice_id"], unique=False)
    op.create_index(
        op.f("ix_payments_mpesa_checkout_request_id"), "payments", ["mpesa_checkout_request_id"], unique=True
    )
    op.create_index(op.f("ix_payments_mpesa_receipt"), "payments", ["mpesa_receipt"], unique=True)
    op.create_index(op.f("ix_payments_organization_id"), "payments", ["organization_id"], unique=False)
    op.create_index(op.f("ix_payments_paid_at"), "payments", ["paid_at"], unique=False)
    op.create_index(op.f("ix_payments_reference_code"), "payments", ["reference_code"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_tenancy_id"), "payments", ["tenancy_id"], unique=False)
    op.create_table(
        "receipts",
        sa.Column("reference_code", sa.String(length=32), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("signature", sa.String(length=128), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["stored_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "reference_code", name="uq_receipt_ref_per_org"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_index(op.f("ix_receipts_organization_id"), "receipts", ["organization_id"], unique=False)
    op.create_index(op.f("ix_receipts_reference_code"), "receipts", ["reference_code"], unique=False)
    op.add_column("organizations", sa.Column("logo_file_id", sa.UUID(), nullable=True))
    op.add_column("organizations", sa.Column("legal_name", sa.String(length=255), nullable=True))
    op.add_column("organizations", sa.Column("address", sa.String(length=512), nullable=True))
    op.add_column("organizations", sa.Column("contact_email", sa.String(length=255), nullable=True))
    op.add_column("organizations", sa.Column("contact_phone", sa.String(length=32), nullable=True))
    op.add_column("organizations", sa.Column("kra_pin", sa.String(length=32), nullable=True))
    op.add_column("organizations", sa.Column("letterhead_note", sa.Text(), nullable=True))
    op.add_column(
        "organizations",
        sa.Column("default_caretaker_cash_limit", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "organizations", sa.Column("default_billing_day", sa.Integer(), nullable=False, server_default="1")
    )
    op.add_column("organizations", sa.Column("trial_reminder_sent_days", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_organizations_logo_file_id",
        "organizations",
        "stored_files",
        ["logo_file_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("users", sa.Column("profile_photo_url", sa.String(length=1024), nullable=True))
    op.add_column(
        "users", sa.Column("always_require_2fa", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "users", sa.Column("inactivity_timeout_minutes", sa.Integer(), nullable=False, server_default="30")
    )
    op.add_column("users", sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "deletion_requested_at")
    op.drop_column("users", "inactivity_timeout_minutes")
    op.drop_column("users", "always_require_2fa")
    op.drop_column("users", "profile_photo_url")
    op.drop_constraint("fk_organizations_logo_file_id", "organizations", type_="foreignkey")
    op.drop_column("organizations", "trial_reminder_sent_days")
    op.drop_column("organizations", "default_billing_day")
    op.drop_column("organizations", "default_caretaker_cash_limit")
    op.drop_column("organizations", "letterhead_note")
    op.drop_column("organizations", "kra_pin")
    op.drop_column("organizations", "contact_phone")
    op.drop_column("organizations", "contact_email")
    op.drop_column("organizations", "address")
    op.drop_column("organizations", "legal_name")
    op.drop_column("organizations", "logo_file_id")
    op.drop_index(op.f("ix_receipts_reference_code"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_organization_id"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_payments_tenancy_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_reference_code"), table_name="payments")
    op.drop_index(op.f("ix_payments_paid_at"), table_name="payments")
    op.drop_index(op.f("ix_payments_organization_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_mpesa_receipt"), table_name="payments")
    op.drop_index(op.f("ix_payments_mpesa_checkout_request_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_meter_readings_unit_id"), table_name="meter_readings")
    op.drop_index(op.f("ix_meter_readings_reading_date"), table_name="meter_readings")
    op.drop_index(op.f("ix_meter_readings_organization_id"), table_name="meter_readings")
    op.drop_table("meter_readings")
    op.drop_index(op.f("ix_invoice_line_items_invoice_id"), table_name="invoice_line_items")
    op.drop_table("invoice_line_items")
    op.drop_index(op.f("ix_vacate_notices_tenancy_id"), table_name="vacate_notices")
    op.drop_index(op.f("ix_vacate_notices_organization_id"), table_name="vacate_notices")
    op.drop_table("vacate_notices")
    op.drop_index(op.f("ix_maintenance_requests_unit_id"), table_name="maintenance_requests")
    op.drop_index(op.f("ix_maintenance_requests_status"), table_name="maintenance_requests")
    op.drop_index(op.f("ix_maintenance_requests_reference_code"), table_name="maintenance_requests")
    op.drop_index(op.f("ix_maintenance_requests_organization_id"), table_name="maintenance_requests")
    op.drop_table("maintenance_requests")
    op.drop_index(op.f("ix_invoices_tenancy_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_reference_code"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_organization_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_due_date"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_tenancies_unit_id"), table_name="tenancies")
    op.drop_index(op.f("ix_tenancies_tenant_id"), table_name="tenancies")
    op.drop_index(op.f("ix_tenancies_status"), table_name="tenancies")
    op.drop_index(op.f("ix_tenancies_reference_code"), table_name="tenancies")
    op.drop_index(op.f("ix_tenancies_organization_id"), table_name="tenancies")
    op.drop_index(op.f("ix_tenancies_end_date"), table_name="tenancies")
    op.drop_table("tenancies")
    op.drop_index(op.f("ix_units_status"), table_name="units")
    op.drop_index(op.f("ix_units_reference_code"), table_name="units")
    op.drop_index(op.f("ix_units_property_id"), table_name="units")
    op.drop_index(op.f("ix_units_organization_id"), table_name="units")
    op.drop_index(op.f("ix_units_is_archived"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_tenant_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_organization_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_notification_type"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_caretaker_assignments_user_id"), table_name="caretaker_assignments")
    op.drop_index(op.f("ix_caretaker_assignments_property_id"), table_name="caretaker_assignments")
    op.drop_index(op.f("ix_caretaker_assignments_organization_id"), table_name="caretaker_assignments")
    op.drop_table("caretaker_assignments")
    op.drop_index(op.f("ix_verification_tokens_user_id"), table_name="verification_tokens")
    op.drop_index(op.f("ix_verification_tokens_token_hash"), table_name="verification_tokens")
    op.drop_table("verification_tokens")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_refresh_token_hash"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_organization_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_device_fingerprint"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_trusted_devices_user_id"), table_name="trusted_devices")
    op.drop_index(op.f("ix_trusted_devices_organization_id"), table_name="trusted_devices")
    op.drop_index(op.f("ix_trusted_devices_device_fingerprint"), table_name="trusted_devices")
    op.drop_table("trusted_devices")
    op.drop_index(op.f("ix_tenants_reference_code"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_phone_number"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_organization_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_national_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_is_archived"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_full_name"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_email"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_index(op.f("ix_push_subscriptions_organization_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index(op.f("ix_properties_reference_code"), table_name="properties")
    op.drop_index(op.f("ix_properties_organization_id"), table_name="properties")
    op.drop_index(op.f("ix_properties_is_archived"), table_name="properties")
    op.drop_index(op.f("ix_properties_county"), table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_notification_preferences_user_id"), table_name="notification_preferences")
    op.drop_index(op.f("ix_notification_preferences_organization_id"), table_name="notification_preferences")
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_lease_templates_organization_id"), table_name="lease_templates")
    op.drop_table("lease_templates")
    op.drop_index(op.f("ix_invitations_token_hash"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_phone_number"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_organization_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_stored_files_storage_key"), table_name="stored_files")
    op.drop_index(op.f("ix_stored_files_organization_id"), table_name="stored_files")
    op.drop_index(op.f("ix_stored_files_entity_type"), table_name="stored_files")
    op.drop_index(op.f("ix_stored_files_entity_id"), table_name="stored_files")
    op.drop_table("stored_files")
    # ### end Alembic commands ###
